apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: fastapi
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg2://fastapi_user:StrongPassword123%21@fastapi-devops-dev-postgres.cluk6yyye4gl.ap-south-1.rds.amazonaws.com:5432/fastapi

